version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: phoenix
    versions:
    - 1.5.8
  - dependency-name: timex
    versions:
    - 3.6.3
    - 3.6.4
  - dependency-name: oban
    versions:
    - 2.4.2
    - 2.4.3
    - 2.5.0
  - dependency-name: ex_machina
    versions:
    - 2.5.0
    - 2.6.0
  - dependency-name: sentry
    versions:
    - 8.0.5
  - dependency-name: excoveralls
    versions:
    - 0.13.4
    - 0.14.0
  - dependency-name: credo
    versions:
    - 1.5.4
    - 1.5.5
  - dependency-name: floki
    versions:
    - 0.30.0
  - dependency-name: phoenix_live_view
    versions:
    - 0.15.4
  - dependency-name: ecto_sql
    versions:
    - 3.5.4
  - dependency-name: postgrex
    versions:
    - 0.15.8
  - dependency-name: hackney
    versions:
    - 1.17.0
  - dependency-name: ecto_psql_extras
    versions:
    - 0.4.2
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 99
  assignees:
  - markevich
  ignore:
  - dependency-name: chart.js
    versions:
    - "> 3.0.0.pre.beta.4, < 3.1"
  - dependency-name: terser-webpack-plugin
    versions:
    - "> 4.2.1, < 4.3"
  - dependency-name: webpack-cli
    versions:
    - ">= 4.0.a, < 4.1"
  - dependency-name: webpack-cli
    versions:
    - ">= 4.1.a, < 4.2"
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.16
    - 7.12.17
    - 7.13.8
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.2
    - 5.23.0
    - 5.24.2
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.1.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.4
    - 1.3.5
    - 1.3.6
    - 1.3.8
    - 1.3.9
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.7
    - 1.32.8
  - dependency-name: postcss
    versions:
    - 8.2.4
    - 8.2.5
    - 8.2.6
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
    - 11.0.1
  - dependency-name: date-fns
    versions:
    - 2.17.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  - dependency-name: terser-webpack-plugin
    versions:
    - 5.1.1
  - dependency-name: css-minimizer-webpack-plugin
    versions:
    - 1.2.0
