language: elixir
elixir: '1.9.1'
otp_release: '22.0'

cache:
  directories:
    - assets/node_modules
    - _build
    - deps

env:
  - MIX_ENV=test TRAVIS_NODE_VERSION="12.6.0"

services:
  - postgresql

addons:
  postgresql: "11.0"

install:
  - cp config/test.secret.example.exs config/test.secret.exs
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION

before_script:
  - mix do ecto.create, ecto.migrate
  - cd assets && npm install && npm run deploy && cd ../

script:
  - mix format --check-formatted
  - mix coveralls.travis
  - mix credo --strict
  - mix hex.audit
  # - mix hex.audit
  # - cd assets && npm test
